### ISSUE TITLE
Feature Request: Open in multiple panes

### ISSUE THREAD

**Issue by colelawrence** [BenjaminRichardson/OpenFileFamily#1]
This is a perfect extension for use with something like an Angular project where we have multiple files for each component, such as `[".component.ts", ".component.scss", ".component.html"]`.

I think it could be helpful to have the ability to open these families in separate panes. Preferrably, this would be a separate command, rather than a setting.

Thanks!

**Comment by BenjaminRichardson** [comment]
Hi @colelawrence! thanks for the feedback.

Opening all the files associated with a component is exactly how I imagined this extension being used. 

The docs are still a work in progress but if you want them open in separate panes, you would need to edit the config to:
```
"openFileFamily.families": [
    [[".component.ts"], [".component.scss"], [".component.html" ]]
]`
```

If you want to open them all in the same pane it would be:
```
"openFileFamily.families": [
    [".component.ts", ".component.scss", ".component.html" ]
]
```

If I understand correctly, you'd like a way to list the files (like in the second example), and  either open the files in a single pane or in separate panes, depending on the command. 

That sounds reasonable to me. I'm imagining an command "open family individual pane" which will ignore any groupings of a family and open every file in a separate pane. 

Would that satisfy your use case?

**Comment by colelawrence** [comment]
Wowee! Perfect. Thanks for the heads up.
